In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
import pandas as pd

provider_features = pd.read_csv(
    "../data/processed/provider_features.csv"
)

print("Shape:", provider_features.shape)

Shape: (5410, 23)

In [3]:
provider_features.head()

,Provider,InpatientClaims,OutpatientClaims,TotalClaims,InpatientClaimRatio,OutpatientClaimRatio,InpatientReimbursement,InpatientAverageClaim,InpatientMaximumClaim,OutpatientReimbursement,...,TotalAverageClaim,UniqueBeneficiaries,ClaimsPerBeneficiary,UniqueDiagnosisCount,UniqueProcedureCount,AverageHospitalStay,MaximumHospitalStay,LongHospitalStayCount,AverageChronicConditions,PotentialFraud
0,PRV51001,5.0,20.0,25.0,0.200000,0.800000,97000.0,19400.000000,42000.0,7640.0,...,4185.600000,24,1.041667,83,3,5.000000,14.0,0.0,5.541667,No
1,PRV51003,62.0,70.0,132.0,0.469697,0.530303,573000.0,9241.935484,57000.0,32670.0,...,4588.409091,117,1.128205,394,39,5.161290,27.0,0.0,4.367521,Yes
2,PRV51007,3.0,69.0,72.0,0.041667,0.958333,19000.0,6333.333333,10000.0,14710.0,...,350.134228,58,1.241379,178,1,5.333333,7.0,0.0,3.879310,No
3,PRV51008,2.0,41.0,43.0,0.046512,0.953488,25000.0,12500.000000,21000.0,10630.0,...,241.124464,36,1.194444,103,2,4.000000,5.0,0.0,4.083333,No
4,PRV51011,1.0,57.0,58.0,0.017241,0.982759,5000.0,5000.000000,5000.0,11630.0,...,468.194444,53,1.094340,131,0,5.000000,5.0,0.0,4.528302,No

In [4]:
from src.components.data_transformation import (
    DataTransformation
)

data_transformer = DataTransformation(
    test_size=0.20,
    random_state=42
)

X_train, X_test, y_train, y_test = (
    data_transformer.transform(
        provider_features=provider_features
    )
)

In [5]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\nTraining target:")
print(y_train.value_counts())

print("\nTesting target:")
print(y_test.value_counts())

X_train: (4328, 21)
X_test: (1082, 21)

Training target:
PotentialFraud
0    3923
1     405
Name: count, dtype: int64

Testing target:
PotentialFraud
0    981
1    101
Name: count, dtype: int64

In [6]:
from src.components.model_trainer import ModelTrainer

trainer = ModelTrainer(
    random_state=42,
    cv_splits=5,
    n_iter=20,
    scoring="f1"
)

In [7]:
best_model, results_df = trainer.train(
    X_train=X_train,
    X_test=X_test,
    y_train=y_train,
    y_test=y_test,
    artifact_dir="../artifacts"
)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits

In [8]:
results_df[
    [
        "Model",
        "Precision",
        "Recall",
        "F1",
        "PR-AUC",
        "ROC-AUC",
        "TestPrecision",
        "TestRecall",
        "TestF1",
        "TestPR-AUC",
        "TestROC-AUC",
    ]
]

,Model,Precision,Recall,F1,PR-AUC,ROC-AUC,TestPrecision,TestRecall,TestF1,TestPR-AUC,TestROC-AUC
0,LightGBM,0.648590,0.738272,0.690531,0.753625,0.949624,0.638655,0.752475,0.690909,0.764361,0.953306
1,XGBoost,0.669811,0.701235,0.685163,0.748218,0.946630,NaN,NaN,NaN,NaN,NaN
2,Logistic Regression,0.637813,0.691358,0.663507,0.711106,0.945033,NaN,NaN,NaN,NaN,NaN
3,Random Forest,0.635514,0.671605,0.653061,0.691843,0.944333,NaN,NaN,NaN,NaN,NaN

In [2]:
import os
import sys

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

print(project_root)

c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection

In [3]:

from src.components.data_transformation import DataTransformation

In [6]:
import pandas as pd

provider_features = pd.read_csv(
    "../data/processed/provider_features.csv"
)

print("Shape:", provider_features.shape)

Shape: (5410, 40)

In [7]:
data_transformer = DataTransformation(
    test_size=0.20,
    random_state=42
)

In [8]:
X_train, X_test, y_train, y_test = (
    data_transformer.transform(
        provider_features=provider_features
    )
)

In [9]:
X_train, X_test, y_train, y_test = (
    data_transformer.transform(
        provider_features=provider_features
    )
)

In [10]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\ny_train:")
print(y_train.value_counts())

print("\ny_test:")
print(y_test.value_counts())

X_train: (4328, 38)
X_test: (1082, 38)

y_train:
PotentialFraud
0    3923
1     405
Name: count, dtype: int64

y_test:
PotentialFraud
0    981
1    101
Name: count, dtype: int64

In [11]:
import os
import sys

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [12]:
import pandas as pd

from src.components.model_trainer import ModelTrainer

In [13]:
provider_features = pd.read_csv(
    "../data/processed/provider_features.csv"
)

print(provider_features.shape)

(5410, 40)

In [14]:
from src.components.data_transformation import DataTransformation

data_transformer = DataTransformation(
    test_size=0.20,
    random_state=42
)

X_train, X_test, y_train, y_test = (
    data_transformer.transform(
        provider_features=provider_features
    )
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

X_train: (4328, 38)
X_test: (1082, 38)

In [15]:
trainer = ModelTrainer(
    random_state=42,
    cv_folds=5,
    scoring="f1"
)

results_df, best_model, best_threshold = (
    trainer.train_models(
        X_train=X_train,
        y_train=y_train,
        X_test=X_test,
        y_test=y_test,
    )
)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
Fitting 5 folds for each of 96 candidates, totalling 480 fits
Fitting 5 folds for each of 144 candidates, totalling 720 fits
Fitting 5 folds for each of 432 candidates, totalling 2160 fits

In [16]:
results_df[
    [
        "Model",
        "CV_F1",
        "Test_Precision_0.50",
        "Test_Recall_0.50",
        "Test_F1_0.50",
        "Test_PR_AUC",
        "Test_ROC_AUC",
        "BestThreshold",
        "Threshold_Precision",
        "Threshold_Recall",
        "Threshold_F1",
    ]
]

,Model,CV_F1,Test_Precision_0.50,Test_Recall_0.50,Test_F1_0.50,Test_PR_AUC,Test_ROC_AUC,BestThreshold,Threshold_Precision,Threshold_Recall,Threshold_F1
0,Logistic Regression,0.659790,0.604167,0.861386,0.710204,0.799714,0.969439,0.61,0.674603,0.841584,0.748899
1,LightGBM,0.695562,0.695652,0.792079,0.740741,0.820013,0.973840,0.48,0.694915,0.811881,0.748858
2,XGBoost,0.689069,0.686441,0.801980,0.739726,0.811199,0.970691,0.52,0.701754,0.792079,0.744186
3,Random Forest,0.680933,0.634783,0.722772,0.675926,0.762140,0.969046,0.44,0.612403,0.782178,0.686957

In [17]:
import os
import sys

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [18]:
import pandas as pd

provider_features = pd.read_csv(
    "../data/processed/provider_features.csv"
)

print(provider_features.shape)

(5410, 69)

In [19]:
from src.components.data_transformation import DataTransformation

data_transformer = DataTransformation(
    test_size=0.20,
    random_state=42
)

X_train, X_test, y_train, y_test = (
    data_transformer.transform(
        provider_features
    )
)

In [20]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\nTraining target:")
print(y_train.value_counts())

print("\nTesting target:")
print(y_test.value_counts())

X_train: (4328, 67)
X_test: (1082, 67)

Training target:
PotentialFraud
0    3923
1     405
Name: count, dtype: int64

Testing target:
PotentialFraud
0    981
1    101
Name: count, dtype: int64

In [22]:
import numpy as np
print(
    "Remaining missing values:",
    X_train.isna().sum().sum()
)

print(
    "Remaining infinite values:",
    np.isinf(X_train.select_dtypes("number")).sum().sum()
)

Remaining missing values: 14851
Remaining infinite values: 0

In [23]:
from src.components.model_trainer import ModelTrainer

In [24]:
trainer = ModelTrainer(
    random_state=42,
    cv_folds=5,
    scoring="f1"
)

In [25]:
results_df, best_model, best_threshold = (
    trainer.train_models(
        X_train=X_train,
        y_train=y_train,
        X_test=X_test,
        y_test=y_test
    )
)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
Fitting 5 folds for each of 96 candidates, totalling 480 fits
Fitting 5 folds for each of 144 candidates, totalling 720 fits
Fitting 5 folds for each of 432 candidates, totalling 2160 fits

In [26]:
results_df[
    [
        "Model",
        "CV_F1",
        "Test_Precision_0.50",
        "Test_Recall_0.50",
        "Test_F1_0.50",
        "Test_PR_AUC",
        "Test_ROC_AUC",
        "BestThreshold",
        "Threshold_Precision",
        "Threshold_Recall",
        "Threshold_F1"
    ]
]

,Model,CV_F1,Test_Precision_0.50,Test_Recall_0.50,Test_F1_0.50,Test_PR_AUC,Test_ROC_AUC,BestThreshold,Threshold_Precision,Threshold_Recall,Threshold_F1
0,LightGBM,0.698961,0.750000,0.712871,0.730964,0.828557,0.976726,0.10,0.679688,0.861386,0.759825
1,Logistic Regression,0.652813,0.575949,0.900990,0.702703,0.793248,0.971135,0.61,0.664000,0.821782,0.734513
2,XGBoost,0.691131,0.682243,0.722772,0.701923,0.809860,0.974354,0.37,0.675000,0.801980,0.733032
3,Random Forest,0.679473,0.660870,0.752475,0.703704,0.795670,0.973199,0.56,0.714286,0.742574,0.728155

In [27]:
results_df.sort_values(
    by="Test_F1_0.50",
    ascending=False
)[
    [
        "Model",
        "Test_Precision_0.50",
        "Test_Recall_0.50",
        "Test_F1_0.50",
        "Test_PR_AUC",
        "Test_ROC_AUC"
    ]
]

,Model,Test_Precision_0.50,Test_Recall_0.50,Test_F1_0.50,Test_PR_AUC,Test_ROC_AUC
0,LightGBM,0.750000,0.712871,0.730964,0.828557,0.976726
3,Random Forest,0.660870,0.752475,0.703704,0.795670,0.973199
1,Logistic Regression,0.575949,0.900990,0.702703,0.793248,0.971135
2,XGBoost,0.682243,0.722772,0.701923,0.809860,0.974354

In [28]:
results_df.sort_values(
    by="Threshold_F1",
    ascending=False
)[
    [
        "Model",
        "BestThreshold",
        "Threshold_Precision",
        "Threshold_Recall",
        "Threshold_F1"
    ]
]

,Model,BestThreshold,Threshold_Precision,Threshold_Recall,Threshold_F1
0,LightGBM,0.10,0.679688,0.861386,0.759825
1,Logistic Regression,0.61,0.664000,0.821782,0.734513
2,XGBoost,0.37,0.675000,0.801980,0.733032
3,Random Forest,0.56,0.714286,0.742574,0.728155

In [30]:
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
)

In [31]:
# Predictions
train_probabilities = best_model.predict_proba(X_train)[:, 1]
test_probabilities = best_model.predict_proba(X_test)[:, 1]

# Use the normal 0.50 threshold
train_predictions = (
    train_probabilities >= 0.50
).astype(int)

test_predictions = (
    test_probabilities >= 0.50
).astype(int)

In [32]:
train_metrics = {
    "Precision": precision_score(
        y_train,
        train_predictions,
        zero_division=0,
    ),
    "Recall": recall_score(
        y_train,
        train_predictions,
        zero_division=0,
    ),
    "F1": f1_score(
        y_train,
        train_predictions,
        zero_division=0,
    ),
    "PR-AUC": average_precision_score(
        y_train,
        train_probabilities,
    ),
    "ROC-AUC": roc_auc_score(
        y_train,
        train_probabilities,
    ),
}


test_metrics = {
    "Precision": precision_score(
        y_test,
        test_predictions,
        zero_division=0,
    ),
    "Recall": recall_score(
        y_test,
        test_predictions,
        zero_division=0,
    ),
    "F1": f1_score(
        y_test,
        test_predictions,
        zero_division=0,
    ),
    "PR-AUC": average_precision_score(
        y_test,
        test_probabilities,
    ),
    "ROC-AUC": roc_auc_score(
        y_test,
        test_probabilities,
    ),
}

In [33]:
performance_df = pd.DataFrame(
    {
        "Metric": list(train_metrics.keys()),
        "Training": list(train_metrics.values()),
        "Testing": list(test_metrics.values()),
    }
)

performance_df

      Metric  Training   Testing
0  Precision       1.0  0.750000
1     Recall       1.0  0.712871
2         F1       1.0  0.730964
3     PR-AUC       1.0  0.828557
4    ROC-AUC       1.0  0.976726

In [34]:
print("Best Model:", type(best_model).__name__)
print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Best Model: Pipeline
Training samples: 4328
Testing samples: 1082

In [1]:
import os
import sys

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [2]:
import pandas as pd

provider_features = pd.read_csv(
    "../data/processed/provider_features.csv"
)

print(provider_features.shape)

(5410, 69)

In [3]:
from src.components.data_transformation import DataTransformation

data_transformer = DataTransformation(
    test_size=0.20,
    random_state=42,
)

X_train, X_test, y_train, y_test = (
    data_transformer.transform(
        provider_features
    )
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

X_train: (4328, 67)
X_test: (1082, 67)

In [4]:
from src.components.model_trainer import ModelTrainer

trainer = ModelTrainer(
    random_state=42,
    cv_folds=5,
    scoring="f1",
    search_iterations=12,
)

results_df, best_model, best_threshold = (
    trainer.train_models(
        X_train=X_train,
        y_train=y_train,
        X_test=X_test,
        y_test=y_test,
    )
)

In [5]:
results_df[
    [
        "Model",
        "Strategy",
        "CV_F1",
        "Train_Precision",
        "Train_Recall",
        "Train_F1",
        "Test_Precision",
        "Test_Recall",
        "Test_F1",
        "Test_PR_AUC",
        "Test_ROC_AUC",
        "BestThreshold",
        "Threshold_Precision",
        "Threshold_Recall",
        "Threshold_F1",
        "Train_Test_F1_Gap",
    ]
]

,Model,Strategy,CV_F1,Train_Precision,Train_Recall,Train_F1,Test_Precision,Test_Recall,Test_F1,Test_PR_AUC,Test_ROC_AUC,BestThreshold,Threshold_Precision,Threshold_Recall,Threshold_F1,Train_Test_F1_Gap
0,LightGBM,class_weight,0.707323,0.884701,0.985185,0.932243,0.790000,0.782178,0.786070,0.838221,0.979118,0.55,0.699519,0.718519,0.708892,0.146173
1,XGBoost,class_weight,0.696644,0.904328,0.980247,0.940758,0.754902,0.762376,0.758621,0.829758,0.977079,0.54,0.692494,0.706173,0.699267,0.182138
2,LightGBM,smote,0.681043,0.701863,0.837037,0.763514,0.661290,0.811881,0.728889,0.827849,0.974869,0.51,0.630165,0.753086,0.686164,0.034625
3,XGBoost,smote,0.676454,0.655238,0.849383,0.739785,0.617188,0.782178,0.689956,0.798911,0.970327,0.52,0.611002,0.767901,0.680525,0.049829
4,Random Forest,class_weight,0.674577,0.748106,0.975309,0.846731,0.629921,0.792079,0.701754,0.787264,0.971871,0.50,0.606299,0.760494,0.674699,0.144977
5,Random Forest,smote,0.669235,0.682927,0.898765,0.776119,0.589552,0.782178,0.672340,0.771626,0.971296,0.57,0.596929,0.767901,0.671706,0.103779
6,Logistic Regression,smote,0.611888,0.618956,0.790123,0.694143,0.625000,0.841584,0.717300,0.792317,0.966623,0.75,0.593385,0.753086,0.663765,-0.023156
7,Logistic Regression,class_weight,0.603277,0.654584,0.758025,0.702517,0.645161,0.792079,0.711111,0.799368,0.970085,0.80,0.619355,0.711111,0.662069,-0.008594

In [2]:
import os

print(os.getcwd())

c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\notebooks

In [4]:
import os

os.chdir(
    r"C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection"
)

print(os.getcwd())

C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection

In [5]:
import os

print(os.path.exists("src"))
print(os.path.exists("src/components"))
print(os.path.exists("src/components/model_training.py"))

True
True
False

In [1]:
from src.components.data_transformation import DataTransformation

ModuleNotFoundError: No module named 'src'

In [2]:
import os
import sys

project_root = os.path.abspath(
    os.path.join(os.getcwd(), "..")
)

print("Project root:")
print(project_root)

print("\nProject root exists:")
print(os.path.exists(project_root))

print("\nsrc exists:")
print(os.path.exists(
    os.path.join(project_root, "src")
))

Project root:
c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection

Project root exists:
True

src exists:
True

In [3]:
import sys

if project_root not in sys.path:
    sys.path.insert(0, project_root)

print(sys.path[0])

c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection

In [4]:
from src.components.data_transformation import DataTransformation

In [5]:
data_transformer = DataTransformation()

X_train, X_test, y_train, y_test = (
    data_transformer.transform_from_processed_data()
)

In [6]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\ny_train:")
print(y_train.value_counts())

print("\ny_test:")
print(y_test.value_counts())

X_train: (4328, 71)
X_test: (1082, 71)

y_train:
PotentialFraud
0    3923
1     405
Name: count, dtype: int64

y_test:
PotentialFraud
0    981
1    101
Name: count, dtype: int64

In [7]:
from src.components.data_transformation import DataTransformation

data_transformer = DataTransformation(
    test_size=0.20,
    random_state=42
)

In [8]:
provider_features = data_transformer.load_processed_data()

print("Processed data shape:", provider_features.shape)
print("Number of columns:", provider_features.shape[1])

Processed data shape: (5410, 73)
Number of columns: 73

In [9]:
X_train, X_test, y_train, y_test = (
    data_transformer.transform_from_processed_data()
)

In [10]:
print("=" * 60)
print("FINAL DATA CHECK")
print("=" * 60)

print("Provider features:", provider_features.shape)
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\nTraining target:")
print(y_train.value_counts())

print("\nTesting target:")
print(y_test.value_counts())

print("=" * 60)

============================================================
FINAL DATA CHECK
============================================================
Provider features: (5410, 73)
X_train: (4328, 71)
X_test: (1082, 71)

Training target:
PotentialFraud
0    3923
1     405
Name: count, dtype: int64

Testing target:
PotentialFraud
0    981
1    101
Name: count, dtype: int64
============================================================

In [11]:
from src.components.model_trainer import ModelTraining

In [12]:
model_trainer = ModelTraining(
    random_state=42,
    cv_folds=5,
    n_iter=20
)

In [13]:
best_model, model_results, best_threshold = (
    model_trainer.train_models(
        X_train=X_train,
        X_test=X_test,
        y_train=y_train,
        y_test=y_test
    )
)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits

====================================================================================================
MODEL TRAINING RESULTS
====================================================================================================
              Model    CV_F1  Train_Precision  Train_Recall  Train_F1  Train_PR_AUC  Train_ROC_AUC  Test_Precision  Test_Recall  Test_F1  Test_PR_AUC  Test_ROC_AUC  BestThreshold    F1_Gap
            XGBoost 0.686541         0.865385      1.000000  0.927835      0.997935       0.999792        0.689076     0.811881 0.745455     0.822546      0.972669           0.58  0.182381
           LightGBM 0.695068         1.000000      1.000000  1.000000      1.000000       1.000000        0.730000     0.722772 0.726368     0.817671      0.974748           0.53  0.273632
      Random Forest 0.666841         0.772727      0.923457  0.841395      0.953038       0.993610        0.642857     0.801980 0.713656     0.772645      0.972497           0.58  0.127738
Logistic Regression 0.644603         0.660422      0.696296  0.677885      0.735953       0.951809        0.689320     0.702970 0.696078     0.788835      0.968379           0.69 -0.018194

====================================================================================================
Best Model: XGBoost
Best Threshold: 0.58
====================================================================================================

In [2]:
import os
import sys

PROJECT_ROOT = os.path.abspath(
    os.path.join(os.getcwd(), "..")
)

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

print("Project root:", PROJECT_ROOT)
print("src exists:", os.path.exists(
    os.path.join(PROJECT_ROOT, "src")
))

Project root: c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection
src exists: True

In [4]:
from src.components.data_transformation import DataTransformation

data_transformer = DataTransformation(
    test_size=0.20,
    random_state=42
)

In [5]:
X_train, X_test, y_train, y_test = (
    data_transformer.transform_from_processed_data()
)

In [9]:
import pandas as pd
import numpy as np

# ---------------------------------------------------------
# FEATURE AUDIT
# ---------------------------------------------------------

print("=" * 80)
print("FEATURE AUDIT")
print("=" * 80)

# X_train is already the transformed data.
# Get feature names from the preprocessor if available.

try:
    feature_names = data_transformer.preprocessor.get_feature_names_out()
except Exception:
    feature_names = [
        f"Feature_{i}"
        for i in range(X_train.shape[1])
    ]

print("\nNumber of model features:", len(feature_names))

# ---------------------------------------------------------
# 1. CONSTANT FEATURES
# ---------------------------------------------------------

X_train_df = pd.DataFrame(
    X_train,
    columns=feature_names
)

constant_features = [
    col
    for col in X_train_df.columns
    if X_train_df[col].nunique() <= 1
]

print("\n" + "-" * 80)
print("1. CONSTANT FEATURES")
print("-" * 80)

if constant_features:
    print(constant_features)
else:
    print("No constant features found.")


# ---------------------------------------------------------
# 2. MISSING VALUES AFTER TRANSFORMATION
# ---------------------------------------------------------

print("\n" + "-" * 80)
print("2. MISSING VALUES")
print("-" * 80)

missing_count = X_train_df.isnull().sum().sum()

print("Total missing values:", missing_count)

if missing_count == 0:
    print("No missing values after preprocessing.")


# ---------------------------------------------------------
# 3. INFINITE VALUES
# ---------------------------------------------------------

print("\n" + "-" * 80)
print("3. INFINITE VALUES")
print("-" * 80)

infinite_count = np.isinf(
    X_train_df.to_numpy()
).sum()

print("Total infinite values:", infinite_count)


# ---------------------------------------------------------
# 4. HIGHLY CORRELATED FEATURES
# ---------------------------------------------------------

print("\n" + "-" * 80)
print("4. HIGHLY CORRELATED FEATURES")
print("-" * 80)

correlation_matrix = X_train_df.corr().abs()

upper_triangle = correlation_matrix.where(
    np.triu(
        np.ones(correlation_matrix.shape),
        k=1
    ).astype(bool)
)

high_correlation_pairs = []

for column in upper_triangle.columns:

    for row in upper_triangle.index:

        value = upper_triangle.loc[row, column]

        if pd.notna(value) and value >= 0.90:

            high_correlation_pairs.append(
                (
                    row,
                    column,
                    round(value, 4)
                )
            )

high_correlation_pairs = sorted(
    high_correlation_pairs,
    key=lambda x: x[2],
    reverse=True
)

if high_correlation_pairs:

    for pair in high_correlation_pairs[:30]:
        print(pair)

else:
    print("No feature pairs with correlation >= 0.90.")


# ---------------------------------------------------------
# 5. FEATURE VARIANCE
# ---------------------------------------------------------

print("\n" + "-" * 80)
print("5. LOW VARIANCE FEATURES")
print("-" * 80)

variance = X_train_df.var().sort_values()

print(
    variance.head(15)
)


# ---------------------------------------------------------
# 6. FEATURE SUMMARY
# ---------------------------------------------------------

print("\n" + "-" * 80)
print("6. FEATURE SUMMARY")
print("-" * 80)

summary = pd.DataFrame({
    "Feature": X_train_df.columns,
    "Mean": X_train_df.mean().values,
    "Std": X_train_df.std().values,
    "Min": X_train_df.min().values,
    "Max": X_train_df.max().values,
    "Unique": X_train_df.nunique().values
})

print(
    summary.head(20).to_string(index=False)
)

print("\nFeature audit completed.")

================================================================================
FEATURE AUDIT
================================================================================

Number of model features: 71

--------------------------------------------------------------------------------
1. CONSTANT FEATURES
--------------------------------------------------------------------------------
['Feature_8']

--------------------------------------------------------------------------------
2. MISSING VALUES
--------------------------------------------------------------------------------
Total missing values: 0
No missing values after preprocessing.

--------------------------------------------------------------------------------
3. INFINITE VALUES
--------------------------------------------------------------------------------
Total infinite values: 0

--------------------------------------------------------------------------------
4. HIGHLY CORRELATED FEATURES
--------------------------------------------------------------------------------
('Feature_25', 'Feature_26', np.float64(1.0))
('Feature_34', 'Feature_49', np.float64(1.0))
('Feature_27', 'Feature_56', np.float64(1.0))
('Feature_10', 'Feature_12', np.float64(0.9999))
('Feature_5', 'Feature_7', np.float64(0.9998))
('Feature_4', 'Feature_6', np.float64(0.9995))
('Feature_0', 'Feature_24', np.float64(0.9994))
('Feature_25', 'Feature_55', np.float64(0.9983))
('Feature_26', 'Feature_55', np.float64(0.9983))
('Feature_55', 'Feature_57', np.float64(0.9979))
('Feature_13', 'Feature_22', np.float64(0.9961))
('Feature_25', 'Feature_57', np.float64(0.9961))
('Feature_26', 'Feature_57', np.float64(0.9961))
('Feature_0', 'Feature_69', np.float64(0.9958))
('Feature_24', 'Feature_69', np.float64(0.9956))
('Feature_13', 'Feature_14', np.float64(0.9943))
('Feature_14', 'Feature_22', np.float64(0.991))
('Feature_1', 'Feature_69', np.float64(0.9806))
('Feature_0', 'Feature_1', np.float64(0.9786))
('Feature_1', 'Feature_24', np.float64(0.9783))
('Feature_1', 'Feature_9', np.float64(0.9774))
('Feature_62', 'Feature_63', np.float64(0.9722))
('Feature_1', 'Feature_66', np.float64(0.9658))
('Feature_0', 'Feature_66', np.float64(0.9635))
('Feature_66', 'Feature_69', np.float64(0.9631))
('Feature_24', 'Feature_66', np.float64(0.9627))
('Feature_23', 'Feature_24', np.float64(0.9618))
('Feature_17', 'Feature_21', np.float64(0.9605))
('Feature_23', 'Feature_69', np.float64(0.9581))
('Feature_9', 'Feature_69', np.float64(0.9576))

--------------------------------------------------------------------------------
5. LOW VARIANCE FEATURES
--------------------------------------------------------------------------------
Feature_8     0.000000
Feature_2     1.000231
Feature_11    1.000231
Feature_5     1.000231
Feature_15    1.000231
Feature_23    1.000231
Feature_21    1.000231
Feature_17    1.000231
Feature_26    1.000231
Feature_54    1.000231
Feature_40    1.000231
Feature_43    1.000231
Feature_50    1.000231
Feature_65    1.000231
Feature_4     1.000231
dtype: float64

--------------------------------------------------------------------------------
6. FEATURE SUMMARY
--------------------------------------------------------------------------------
   Feature          Mean      Std       Min       Max  Unique
 Feature_0 -3.283469e-18 1.000116 -0.314264 21.968839     130
 Feature_1  9.850408e-18 1.000116 -0.538347 24.171362     602
 Feature_2 -1.276449e-16 1.000116 -2.997257 14.628657     871
 Feature_3  1.432413e-16 1.000116 -1.920604  7.200835     104
 Feature_4 -7.880326e-17 1.000116 -3.241363 16.255097     673
 Feature_5  1.001458e-16 1.000116 -2.258944  3.044602      36
 Feature_6 -4.596857e-17 1.000116 -3.246345 16.290097     670
 Feature_7 -5.910245e-17 1.000116 -2.259929  3.199049      37
 Feature_8  0.000000e+00 0.000000  0.000000  0.000000       1
 Feature_9 -9.850408e-18 1.000116 -0.559105 23.959901      52
Feature_10  1.264136e-16 1.000116 -1.644804  6.356216     257
Feature_11 -6.566938e-18 1.000116 -0.282723 13.946485     181
Feature_12 -5.828158e-17 1.000116 -1.644793  6.356334     259
Feature_13 -9.029540e-18 1.000116 -0.356621 32.009891     514
Feature_14  1.313388e-17 1.000116 -0.368718 31.727044    2401
Feature_15 -4.925204e-18 1.000116 -0.210776 64.978352    3221
Feature_16  1.477561e-17 1.000116 -0.636071 24.529953     202
Feature_17  2.626775e-17 1.000116 -1.028426 14.172059    2089
Feature_18 -8.660150e-17 1.000116 -1.855470  0.985558      23
Feature_19  1.641735e-18 1.000116 -0.208400 61.177596    1506

Feature audit completed.

In [10]:
# ---------------------------------------------------------
# ORIGINAL PROVIDER FEATURE AUDIT
# ---------------------------------------------------------

import os
import pandas as pd
import numpy as np

processed_path = os.path.join(
    PROJECT_ROOT,
    "data",
    "processed",
    "provider_features.csv"
)

provider_features = pd.read_csv(
    processed_path
)

print("=" * 80)
print("ORIGINAL PROVIDER FEATURE AUDIT")
print("=" * 80)

print("\nShape:", provider_features.shape)

print("\nColumns:")
print(provider_features.columns.tolist())


# ---------------------------------------------------------
# Missing percentage
# ---------------------------------------------------------

missing_report = (
    provider_features.isnull()
    .mean()
    .mul(100)
    .sort_values(
        ascending=False
    )
)

print("\n" + "-" * 80)
print("MISSING VALUE PERCENTAGE")
print("-" * 80)

print(
    missing_report[
        missing_report > 0
    ].to_string()
)


# ---------------------------------------------------------
# Unique values
# ---------------------------------------------------------

unique_report = (
    provider_features
    .nunique()
    .sort_values()
)

print("\n" + "-" * 80)
print("LOW UNIQUE-VALUE FEATURES")
print("-" * 80)

print(
    unique_report.head(20)
)


# ---------------------------------------------------------
# Constant columns
# ---------------------------------------------------------

constant_columns = [
    column
    for column in provider_features.columns
    if provider_features[column].nunique(dropna=False) <= 1
]

print("\n" + "-" * 80)
print("CONSTANT COLUMNS")
print("-" * 80)

print(
    constant_columns
    if constant_columns
    else "None"
)


# ---------------------------------------------------------
# Duplicate columns
# ---------------------------------------------------------

duplicate_columns = []

columns = provider_features.columns

for i in range(len(columns)):

    for j in range(i + 1, len(columns)):

        col1 = columns[i]
        col2 = columns[j]

        if provider_features[col1].equals(
            provider_features[col2]
        ):

            duplicate_columns.append(
                (col1, col2)
            )

print("\n" + "-" * 80)
print("DUPLICATE COLUMNS")
print("-" * 80)

print(
    duplicate_columns
    if duplicate_columns
    else "None"
)

================================================================================
ORIGINAL PROVIDER FEATURE AUDIT
================================================================================

Shape: (5410, 73)

Columns:
['Provider', 'PotentialFraud', 'InpatientClaims', 'InpatientReimbursement', 'InpatientAverageClaim', 'InpatientMaximumClaim', 'AverageHospitalStay', 'MaximumHospitalStay', 'AverageInpatientClaimDuration', 'MaximumInpatientClaimDuration', 'AverageInpatientDeductible', 'LongHospitalStayCount', 'LongHospitalStayRatio', 'HighValueInpatientClaimRatio', 'LongClaimDurationRatio', 'OutpatientClaims', 'OutpatientReimbursement', 'OutpatientAverageClaim', 'OutpatientMaximumClaim', 'AverageOutpatientClaimDuration', 'MaximumOutpatientClaimDuration', 'AverageOutpatientDeductible', 'HighValueOutpatientClaimRatio', 'LongOutpatientClaimDurationRatio', 'TotalClaims', 'TotalReimbursement', 'TotalDeductiblePaid', 'InpatientClaimRatio', 'OutpatientClaimRatio', 'TotalAverageClaim', 'UniqueBeneficiaries', 'MaximumBeneficiaryClaims', 'ClaimsPerBeneficiary', 'BeneficiaryConcentration', 'AverageChronicConditions', 'MaximumChronicConditions', 'AverageGender', 'AveragePartACoverageMonths', 'AveragePartBCoverageMonths', 'AverageBeneficiaryIPReimbursement', 'AverageBeneficiaryOPReimbursement', 'AverageBeneficiaryIPDeductible', 'AverageBeneficiaryOPDeductible', 'AverageRenalDiseaseIndicator', 'UniqueBeneficiaryStates', 'UniqueBeneficiaryCounties', 'AverageBeneficiaryAge', 'MedianBeneficiaryAge', 'MinimumBeneficiaryAge', 'MaximumBeneficiaryAge', 'SeniorBeneficiaryRatio', 'FemaleBeneficiaryRatio', 'MedianClaimAmount', 'ClaimAmountStd', 'MaximumClaimAmount', 'AverageClaimDuration', 'MaximumClaimDuration', 'AverageDeductiblePaid', 'ReimbursementPerClaim', 'DeductiblePerClaim', 'DeductibleToReimbursementRatio', 'UniqueAttendingPhysicians', 'UniqueOperatingPhysicians', 'UniqueOtherPhysicians', 'ClaimsPerAttendingPhysician', 'ClaimsPerOperatingPhysician', 'ClaimsPerOtherPhysician', 'UniqueDiagnosisCount', 'UniqueProcedureCount', 'DiagnosesPerClaim', 'ProceduresPerClaim', 'HighValueClaimCount', 'HighValueClaimRatio']

--------------------------------------------------------------------------------
MISSING VALUE PERCENTAGE
--------------------------------------------------------------------------------
ProceduresPerClaim                  62.587800
UniqueProcedureCount                62.587800
AverageInpatientDeductible          61.497227
MaximumHospitalStay                 61.330869
InpatientMaximumClaim               61.330869
AverageInpatientClaimDuration       61.330869
InpatientReimbursement              61.330869
AverageHospitalStay                 61.330869
InpatientAverageClaim               61.330869
HighValueInpatientClaimRatio        61.330869
LongClaimDurationRatio              61.330869
LongHospitalStayCount               61.330869
MaximumInpatientClaimDuration       61.330869
LongHospitalStayRatio               61.330869
ClaimsPerOperatingPhysician         10.295749
ClaimsPerOtherPhysician              9.833641
AverageOutpatientClaimDuration       7.356747
LongOutpatientClaimDurationRatio     7.356747
HighValueOutpatientClaimRatio        7.356747
OutpatientReimbursement              7.356747
MaximumOutpatientClaimDuration       7.356747
AverageOutpatientDeductible          7.356747
OutpatientMaximumClaim               7.356747
OutpatientAverageClaim               7.356747
ClaimAmountStd                       4.436229
DeductibleToReimbursementRatio       0.277264
DiagnosesPerClaim                    0.092421
UniqueDiagnosisCount                 0.092421
AverageDeductiblePaid                0.018484

--------------------------------------------------------------------------------
LOW UNIQUE-VALUE FEATURES
--------------------------------------------------------------------------------
AverageInpatientDeductible          1
PotentialFraud                      2
MaximumChronicConditions           12
MaximumBeneficiaryClaims           23
MaximumOutpatientClaimDuration     23
UniqueBeneficiaryStates            31
MaximumHospitalStay                36
MaximumInpatientClaimDuration      37
MaximumClaimDuration               37
LongHospitalStayCount              56
UniqueBeneficiaryCounties          82
UniqueOperatingPhysicians          90
UniqueProcedureCount               95
InpatientMaximumClaim             106
HighValueClaimCount               110
UniqueOtherPhysicians             115
InpatientClaims                   150
UniqueAttendingPhysicians         168
MedianClaimAmount                 178
HighValueInpatientClaimRatio      214
dtype: int64

--------------------------------------------------------------------------------
CONSTANT COLUMNS
--------------------------------------------------------------------------------
None

--------------------------------------------------------------------------------
DUPLICATE COLUMNS
--------------------------------------------------------------------------------
[('TotalAverageClaim', 'ReimbursementPerClaim')]

In [11]:
print("=" * 80)
print("SELECTED MODEL FEATURE IMPORTANCE")
print("=" * 80)

if hasattr(best_model, "feature_importances_"):

    importances = best_model.feature_importances_

    importance_df = pd.DataFrame({
        "Feature": feature_names,
        "Importance": importances
    })

    importance_df = (
        importance_df
        .sort_values(
            "Importance",
            ascending=False
        )
        .reset_index(drop=True)
    )

    print(
        importance_df.head(30)
        .to_string(index=False)
    )

else:
    print(
        "Selected model does not provide native feature importance."
    )

================================================================================
SELECTED MODEL FEATURE IMPORTANCE
================================================================================
   Feature  Importance
Feature_30         348
 Feature_5         320
Feature_47         309
Feature_23         308
Feature_24         255
 Feature_2         240
Feature_45         237
Feature_53         230
Feature_29         221
Feature_46         216
Feature_34         215
Feature_32         206
Feature_48         205
Feature_38         203
Feature_63         200
Feature_37         190
Feature_62         190
Feature_40         184
Feature_19         180
Feature_20         177
 Feature_1         176
Feature_41         174
Feature_67         173
Feature_44         170
Feature_22         168
Feature_15         167
 Feature_4         167
Feature_64         162
Feature_27         151
Feature_58         142

In [6]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\ny_train:")
print(y_train.value_counts())

print("\ny_test:")
print(y_test.value_counts())

X_train: (4328, 71)
X_test: (1082, 71)

y_train:
PotentialFraud
0    3923
1     405
Name: count, dtype: int64

y_test:
PotentialFraud
0    981
1    101
Name: count, dtype: int64

In [7]:
from src.components.model_trainer import ModelTraining

model_trainer = ModelTraining(
    random_state=42,
    cv_folds=5,
    n_iter=20
)

In [8]:
best_model, model_results, best_threshold = (
    model_trainer.train_models(
        X_train=X_train,
        X_test=X_test,
        y_train=y_train,
        y_test=y_test
    )
)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits

========================================================================================================================
MODEL TRAINING RESULTS
========================================================================================================================
              Model    CV_F1  CV_Threshold_F1  Train_Precision  Train_Recall  Train_F1  Train_PR_AUC  Train_ROC_AUC  Test_Precision  Test_Recall  Test_F1  Test_PR_AUC  Test_ROC_AUC  BestThreshold    F1_Gap
           LightGBM 0.690379         0.691160         0.933180      1.000000  0.965435      1.000000       1.000000        0.694915     0.811881 0.748858     0.832665      0.977614           0.51  0.216577
            XGBoost 0.674180         0.680851         0.955189      1.000000  0.977081      0.999988       0.999999        0.740385     0.762376 0.751220     0.827165      0.973113           0.67  0.225861
Logistic Regression 0.675299         0.675610         0.670588      0.703704  0.686747      0.745903       0.952895        0.714286     0.742574 0.728155     0.793725      0.969671           0.50 -0.041408
      Random Forest 0.670782         0.671626         0.694494      0.965432  0.807851      0.911512       0.990329        0.595588     0.801980 0.683544     0.777603      0.971326           0.49  0.124307

========================================================================================================================
Selected Model: LightGBM
Selected Threshold: 0.51
Model selection was based on cross-validation, not the test set.
========================================================================================================================

In [12]:
print(data_transformer.__dict__.keys())

dict_keys(['test_size', 'random_state'])

In [13]:
import os
import pandas as pd

processed_path = os.path.join(
    PROJECT_ROOT,
    "data",
    "processed",
    "provider_features.csv"
)

provider_features = pd.read_csv(processed_path)

original_feature_names = (
    provider_features
    .drop(columns=["Provider", "PotentialFraud"])
    .columns
    .tolist()
)

print("Number of features:", len(original_feature_names))

print("\nFeature names:")
for i, feature in enumerate(original_feature_names):
    print(i, feature)

Number of features: 71

Feature names:
0 InpatientClaims
1 InpatientReimbursement
2 InpatientAverageClaim
3 InpatientMaximumClaim
4 AverageHospitalStay
5 MaximumHospitalStay
6 AverageInpatientClaimDuration
7 MaximumInpatientClaimDuration
8 AverageInpatientDeductible
9 LongHospitalStayCount
10 LongHospitalStayRatio
11 HighValueInpatientClaimRatio
12 LongClaimDurationRatio
13 OutpatientClaims
14 OutpatientReimbursement
15 OutpatientAverageClaim
16 OutpatientMaximumClaim
17 AverageOutpatientClaimDuration
18 MaximumOutpatientClaimDuration
19 AverageOutpatientDeductible
20 HighValueOutpatientClaimRatio
21 LongOutpatientClaimDurationRatio
22 TotalClaims
23 TotalReimbursement
24 TotalDeductiblePaid
25 InpatientClaimRatio
26 OutpatientClaimRatio
27 TotalAverageClaim
28 UniqueBeneficiaries
29 MaximumBeneficiaryClaims
30 ClaimsPerBeneficiary
31 BeneficiaryConcentration
32 AverageChronicConditions
33 MaximumChronicConditions
34 AverageGender
35 AveragePartACoverageMonths
36 AveragePartBCoverageMonths
37 AverageBeneficiaryIPReimbursement
38 AverageBeneficiaryOPReimbursement
39 AverageBeneficiaryIPDeductible
40 AverageBeneficiaryOPDeductible
41 AverageRenalDiseaseIndicator
42 UniqueBeneficiaryStates
43 UniqueBeneficiaryCounties
44 AverageBeneficiaryAge
45 MedianBeneficiaryAge
46 MinimumBeneficiaryAge
47 MaximumBeneficiaryAge
48 SeniorBeneficiaryRatio
49 FemaleBeneficiaryRatio
50 MedianClaimAmount
51 ClaimAmountStd
52 MaximumClaimAmount
53 AverageClaimDuration
54 MaximumClaimDuration
55 AverageDeductiblePaid
56 ReimbursementPerClaim
57 DeductiblePerClaim
58 DeductibleToReimbursementRatio
59 UniqueAttendingPhysicians
60 UniqueOperatingPhysicians
61 UniqueOtherPhysicians
62 ClaimsPerAttendingPhysician
63 ClaimsPerOperatingPhysician
64 ClaimsPerOtherPhysician
65 UniqueDiagnosisCount
66 UniqueProcedureCount
67 DiagnosesPerClaim
68 ProceduresPerClaim
69 HighValueClaimCount
70 HighValueClaimRatio

In [14]:
import pandas as pd

importance_values = best_model.feature_importances_

importance_df = pd.DataFrame({
    "Feature": original_feature_names,
    "Importance": importance_values
})

importance_df["ImportancePercent"] = (
    importance_df["Importance"]
    / importance_df["Importance"].sum()
    * 100
)

importance_df = (
    importance_df
    .sort_values(
        "Importance",
        ascending=False
    )
    .reset_index(drop=True)
)

print(
    importance_df.head(30).to_string(
        index=False
    )
)

                          Feature  Importance  ImportancePercent
             ClaimsPerBeneficiary         348           3.772358
              MaximumHospitalStay         320           3.468835
            MaximumBeneficiaryAge         309           3.349593
               TotalReimbursement         308           3.338753
              TotalDeductiblePaid         255           2.764228
            InpatientAverageClaim         240           2.601626
             MedianBeneficiaryAge         237           2.569106
             AverageClaimDuration         230           2.493225
         MaximumBeneficiaryClaims         221           2.395664
            MinimumBeneficiaryAge         216           2.341463
                    AverageGender         215           2.330623
         AverageChronicConditions         206           2.233062
           SeniorBeneficiaryRatio         205           2.222222
AverageBeneficiaryOPReimbursement         203           2.200542
      ClaimsPerOperatingPhysician         200           2.168022
AverageBeneficiaryIPReimbursement         190           2.059621
      ClaimsPerAttendingPhysician         190           2.059621
   AverageBeneficiaryOPDeductible         184           1.994580
      AverageOutpatientDeductible         180           1.951220
    HighValueOutpatientClaimRatio         177           1.918699
           InpatientReimbursement         176           1.907859
     AverageRenalDiseaseIndicator         174           1.886179
                DiagnosesPerClaim         173           1.875339
            AverageBeneficiaryAge         170           1.842818
                      TotalClaims         168           1.821138
           OutpatientAverageClaim         167           1.810298
              AverageHospitalStay         167           1.810298
          ClaimsPerOtherPhysician         162           1.756098
                TotalAverageClaim         151           1.636856
   DeductibleToReimbursementRatio         142           1.539295

In [15]:
print(
    importance_df.tail(20).to_string(
        index=False
    )
)

                       Feature  Importance  ImportancePercent
          UniqueDiagnosisCount          75           0.813008
        LongClaimDurationRatio          69           0.747967
     UniqueBeneficiaryCounties          69           0.747967
           HighValueClaimRatio          50           0.542005
        OutpatientMaximumClaim          49           0.531165
         AverageDeductiblePaid          44           0.476965
           HighValueClaimCount          42           0.455285
               InpatientClaims          41           0.444444
        FemaleBeneficiaryRatio          39           0.422764
            MaximumClaimAmount          37           0.401084
  HighValueInpatientClaimRatio          36           0.390244
            DeductiblePerClaim          33           0.357724
         ReimbursementPerClaim          32           0.346883
              OutpatientClaims          29           0.314363
           InpatientClaimRatio          26           0.281843
      MaximumChronicConditions          25           0.271003
          OutpatientClaimRatio          18           0.195122
          MaximumClaimDuration          17           0.184282
MaximumOutpatientClaimDuration           5           0.054201
    AverageInpatientDeductible           0           0.000000

In [16]:
# ============================================================
# FRAUD vs NON-FRAUD FEATURE ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

df = provider_features.copy()

# Convert target to numeric temporarily
df["Fraud"] = (
    df["PotentialFraud"]
    .astype(str)
    .str.lower()
    .map({
        "yes": 1,
        "no": 0
    })
)

# Top features from model importance
top_features = (
    importance_df
    .head(20)["Feature"]
    .tolist()
)

print("=" * 100)
print("FRAUD vs NON-FRAUD FEATURE ANALYSIS")
print("=" * 100)

comparison = []

for feature in top_features:

    fraud_values = df.loc[
        df["Fraud"] == 1,
        feature
    ]

    nonfraud_values = df.loc[
        df["Fraud"] == 0,
        feature
    ]

    comparison.append({
        "Feature": feature,

        "Fraud_Median":
            fraud_values.median(),

        "NonFraud_Median":
            nonfraud_values.median(),

        "Fraud_Mean":
            fraud_values.mean(),

        "NonFraud_Mean":
            nonfraud_values.mean(),

        "Missing_Fraud_%":
            fraud_values.isna().mean() * 100,

        "Missing_NonFraud_%":
            nonfraud_values.isna().mean() * 100
    })

comparison_df = pd.DataFrame(comparison)

print(
    comparison_df.to_string(
        index=False
    )
)

====================================================================================================
FRAUD vs NON-FRAUD FEATURE ANALYSIS
====================================================================================================
                          Feature  Fraud_Median  NonFraud_Median    Fraud_Mean  NonFraud_Mean  Missing_Fraud_%  Missing_NonFraud_%
             ClaimsPerBeneficiary      1.192113         1.083333      1.482765       1.310802         0.000000            0.000000
              MaximumHospitalStay     28.000000        11.000000     27.313636      13.288741        13.043478           66.313214
            MaximumBeneficiaryAge     99.258042        95.073238     97.600322      92.018429         0.000000            0.000000
               TotalReimbursement 373450.000000     15055.000000 584350.039526   53193.723491         0.000000            0.000000
              TotalDeductiblePaid  26359.000000       200.000000  49360.219368    3819.074429         0.000000            0.000000
            InpatientAverageClaim  10375.369458      9000.000000  11046.244346    9984.863110        13.043478           66.313214
             MedianBeneficiaryAge     73.997262        73.838467     73.957623      73.845517         0.000000            0.000000
             AverageClaimDuration      2.478220         1.512224      2.973527       1.914981         0.000000            0.000000
         MaximumBeneficiaryClaims      4.000000         2.000000      6.296443       3.327896         0.000000            0.000000
            MinimumBeneficiaryAge     28.798084        40.869268     32.752460      44.792746         0.000000            0.000000
                    AverageGender      1.576042         1.581395      1.577217       1.581198         0.000000            0.000000
         AverageChronicConditions      4.716257         4.500000      4.810170       4.511368         0.000000            0.000000
           SeniorBeneficiaryRatio      0.834793         0.840909      0.828352       0.827720         0.000000            0.000000
AverageBeneficiaryOPReimbursement   2159.959290      2019.646465   2273.113210    2191.723203         0.000000            0.000000
      ClaimsPerOperatingPhysician     11.500000         8.000000     49.825604      19.549989         0.592885           11.296900
AverageBeneficiaryIPReimbursement   7496.887986      4509.536810   9052.076164    5868.975601         0.000000            0.000000
      ClaimsPerAttendingPhysician      4.629545         2.960769     41.473077      13.576232         0.000000            0.000000
   AverageBeneficiaryOPDeductible    617.035292       587.068004    631.565539     628.840769         0.000000            0.000000
      AverageOutpatientDeductible      2.536000         1.818182      4.821369       2.772843         8.695652            7.218597
    HighValueOutpatientClaimRatio      0.046924         0.037037      0.051814       0.049522         8.695652            7.218597

In [17]:
comparison_df["Mean_Difference_%"] = (
    (
        comparison_df["Fraud_Mean"]
        -
        comparison_df["NonFraud_Mean"]
    )
    /
    comparison_df["NonFraud_Mean"].abs().replace(
        0,
        np.nan
    )
) * 100

print(
    comparison_df[
        [
            "Feature",
            "Fraud_Mean",
            "NonFraud_Mean",
            "Mean_Difference_%"
        ]
    ]
    .sort_values(
        "Mean_Difference_%",
        ascending=False
    )
    .to_string(index=False)
)

                          Feature    Fraud_Mean  NonFraud_Mean  Mean_Difference_%
              TotalDeductiblePaid  49360.219368    3819.074429        1192.465499
               TotalReimbursement 584350.039526   53193.723491         998.531934
      ClaimsPerAttendingPhysician     41.473077      13.576232         205.482966
      ClaimsPerOperatingPhysician     49.825604      19.549989         154.862569
              MaximumHospitalStay     27.313636      13.288741         105.539686
         MaximumBeneficiaryClaims      6.296443       3.327896          89.201930
      AverageOutpatientDeductible      4.821369       2.772843          73.878162
             AverageClaimDuration      2.973527       1.914981          55.277139
AverageBeneficiaryIPReimbursement   9052.076164    5868.975601          54.236050
             ClaimsPerBeneficiary      1.482765       1.310802          13.118884
            InpatientAverageClaim  11046.244346    9984.863110          10.629903
         AverageChronicConditions      4.810170       4.511368           6.623309
            MaximumBeneficiaryAge     97.600322      92.018429           6.066060
    HighValueOutpatientClaimRatio      0.051814       0.049522           4.628199
AverageBeneficiaryOPReimbursement   2273.113210    2191.723203           3.713517
   AverageBeneficiaryOPDeductible    631.565539     628.840769           0.433301
             MedianBeneficiaryAge     73.957623      73.845517           0.151811
           SeniorBeneficiaryRatio      0.828352       0.827720           0.076350
                    AverageGender      1.577217       1.581198          -0.251763
            MinimumBeneficiaryAge     32.752460      44.792746         -26.879991

In [18]:
import pandas as pd
import os

processed_path = os.path.join(
    PROJECT_ROOT,
    "data",
    "processed",
    "provider_features.csv"
)

provider_features = pd.read_csv(processed_path)

print("Provider features:", provider_features.shape)

X = provider_features.drop(
    columns=["Provider", "PotentialFraud"]
)

y = provider_features["PotentialFraud"].map({
    "No": 0,
    "Yes": 1
})

print("X:", X.shape)
print("y:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

Provider features: (5410, 81)
X: (5410, 79)
y: (5410,)

Target distribution:
PotentialFraud
0    4904
1     506
Name: count, dtype: int64

In [19]:
print("\nNew feature dtypes:")
print(
    X[
        [
            "HasInpatientActivity",
            "HasOutpatientActivity",
            "InpatientReimbursementRatio",
            "OutpatientReimbursementRatio",
            "ReimbursementPerBeneficiary",
            "DeductiblePerBeneficiary",
            "DurationVariationRatio",
            "ClaimAmountCV"
        ]
    ].dtypes
)

New feature dtypes:
HasInpatientActivity              int64
HasOutpatientActivity             int64
InpatientReimbursementRatio     float64
OutpatientReimbursementRatio    float64
ReimbursementPerBeneficiary     float64
DeductiblePerBeneficiary        float64
DurationVariationRatio          float64
ClaimAmountCV                   float64
dtype: object

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\ny_train:")
print(y_train.value_counts())

print("\ny_test:")
print(y_test.value_counts())

X_train: (4328, 79)
X_test: (1082, 79)

y_train:
PotentialFraud
0    3923
1     405
Name: count, dtype: int64

y_test:
PotentialFraud
0    981
1    101
Name: count, dtype: int64

In [21]:
feature_check = provider_features.copy()

feature_check["Fraud"] = (
    feature_check["PotentialFraud"]
    .map({
        "No": 0,
        "Yes": 1
    })
)

new_features = [
    "HasInpatientActivity",
    "HasOutpatientActivity",
    "InpatientReimbursementRatio",
    "OutpatientReimbursementRatio",
    "ReimbursementPerBeneficiary",
    "DeductiblePerBeneficiary",
    "DurationVariationRatio",
    "ClaimAmountCV"
]

comparison = []

for feature in new_features:

    fraud = feature_check.loc[
        feature_check["Fraud"] == 1,
        feature
    ]

    nonfraud = feature_check.loc[
        feature_check["Fraud"] == 0,
        feature
    ]

    comparison.append({
        "Feature": feature,
        "Fraud_Mean": fraud.mean(),
        "NonFraud_Mean": nonfraud.mean(),
        "Fraud_Median": fraud.median(),
        "NonFraud_Median": nonfraud.median()
    })

new_feature_comparison = pd.DataFrame(comparison)

print(
    new_feature_comparison.to_string(
        index=False
    )
)

                     Feature  Fraud_Mean  NonFraud_Mean  Fraud_Median  NonFraud_Median
        HasInpatientActivity    0.869565       0.336868      1.000000         0.000000
       HasOutpatientActivity    0.913043       0.927814      1.000000         1.000000
 InpatientReimbursementRatio    0.750141       0.276025      0.914364         0.000000
OutpatientReimbursementRatio    0.249859       0.723975      0.085636         1.000000
 ReimbursementPerBeneficiary 4557.465646    1705.386208   3352.917973       478.090226
    DeductiblePerBeneficiary  405.643362     143.703745    303.005078         5.294118
      DurationVariationRatio   11.419302      11.731542     10.733262        11.000000
               ClaimAmountCV   28.375861      14.171791     20.989855         7.060748

In [22]:
print(
    provider_features[
        ["ClaimAmountCV"]
    ].describe()
)

       ClaimAmountCV
count    5169.000000
mean       15.559498
std        22.908582
min         0.000000
25%         3.219243
50%         7.309316
75%        16.384292
max       329.079461

In [23]:
print(
    provider_features[
        ["ClaimAmountCV"]
    ]
    .sort_values(
        "ClaimAmountCV",
        ascending=False
    )
    .head(20)
)

      ClaimAmountCV
1846     329.079461
5369     296.948115
202      269.357860
4527     244.544131
467      224.540752
4577     188.266613
4283     187.899476
52       176.828426
1176     174.553249
4311     157.926818
2937     155.978483
4860     152.213923
3186     151.837039
3190     143.832977
4581     143.718502
2611     143.587692
287      141.261324
2156     137.768377
128      136.948769
382      134.860229

In [24]:
new_features = [
    "HasInpatientActivity",
    "HasOutpatientActivity",
    "InpatientReimbursementRatio",
    "OutpatientReimbursementRatio",
    "ReimbursementPerBeneficiary",
    "DeductiblePerBeneficiary",
    "DurationVariationRatio",
    "ClaimAmountCV"
]

print(
    provider_features[
        new_features
    ].corr()
)

                              HasInpatientActivity  HasOutpatientActivity  \
HasInpatientActivity                      1.000000              -0.354890
HasOutpatientActivity                    -0.354890               1.000000
InpatientReimbursementRatio               0.948535              -0.450115
OutpatientReimbursementRatio             -0.948535               0.450115
ReimbursementPerBeneficiary               0.537051              -0.690138
DeductiblePerBeneficiary                  0.650496              -0.807092
DurationVariationRatio                   -0.305664               0.391410
ClaimAmountCV                             0.503448               0.165576

                              InpatientReimbursementRatio  \
HasInpatientActivity                             0.948535
HasOutpatientActivity                           -0.450115
InpatientReimbursementRatio                      1.000000
OutpatientReimbursementRatio                    -1.000000
ReimbursementPerBeneficiary                      0.640126
DeductiblePerBeneficiary                         0.771047
DurationVariationRatio                          -0.390885
ClaimAmountCV                                    0.486250

                              OutpatientReimbursementRatio  \
HasInpatientActivity                             -0.948535
HasOutpatientActivity                             0.450115
InpatientReimbursementRatio                      -1.000000
OutpatientReimbursementRatio                      1.000000
ReimbursementPerBeneficiary                      -0.640126
DeductiblePerBeneficiary                         -0.771047
DurationVariationRatio                            0.390885
ClaimAmountCV                                    -0.486250

                              ReimbursementPerBeneficiary  \
HasInpatientActivity                             0.537051
HasOutpatientActivity                           -0.690138
InpatientReimbursementRatio                      0.640126
OutpatientReimbursementRatio                    -0.640126
ReimbursementPerBeneficiary                      1.000000
DeductiblePerBeneficiary                         0.837226
DurationVariationRatio                          -0.409106
ClaimAmountCV                                    0.052403

                              DeductiblePerBeneficiary  \
HasInpatientActivity                          0.650496
HasOutpatientActivity                        -0.807092
InpatientReimbursementRatio                   0.771047
OutpatientReimbursementRatio                 -0.771047
ReimbursementPerBeneficiary                   0.837226
DeductiblePerBeneficiary                      1.000000
DurationVariationRatio                       -0.487834
ClaimAmountCV                                -0.000096

                              DurationVariationRatio  ClaimAmountCV
HasInpatientActivity                       -0.305664       0.503448
HasOutpatientActivity                       0.391410       0.165576
InpatientReimbursementRatio                -0.390885       0.486250
OutpatientReimbursementRatio                0.390885      -0.486250
ReimbursementPerBeneficiary                -0.409106       0.052403
DeductiblePerBeneficiary                   -0.487834      -0.000096
DurationVariationRatio                      1.000000       0.014813
ClaimAmountCV                               0.014813       1.000000

In [25]:
cv_check = provider_features[
    [
        "Provider",
        "PotentialFraud",
        "ClaimAmountCV",
        "TotalClaims",
        "MedianClaimAmount",
        "ClaimAmountStd"
    ]
].sort_values(
    "ClaimAmountCV",
    ascending=False
)

print(
    cv_check.head(30).to_string(
        index=False
    )
)

Provider PotentialFraud  ClaimAmountCV  TotalClaims  MedianClaimAmount  ClaimAmountStd
PRV53304             No     329.079461         13.0               40.0    13163.178441
PRV57719             No     296.948115         23.0               40.0    11877.924603
PRV51259             No     269.357860         21.0               80.0    21548.628837
PRV56664             No     244.544131         15.0               60.0    14672.647860
PRV51588             No     224.540752         10.0               55.0    12349.741383
PRV56726             No     188.266613         16.0               75.0    14119.995987
PRV56354             No     187.899476         11.0               90.0    16910.952825
PRV51067            Yes     176.828426         58.0               85.0    15030.416216
PRV52467            Yes     174.553249        103.0               70.0    12218.727432
PRV56390             No     157.926818          5.0               80.0    12634.145400
PRV54661             No     155.978483         19.0              100.0    15597.848348
PRV57102             No     152.213923         16.0               75.0    11416.044247
PRV54993             No     151.837039         53.0               90.0    13665.333506
PRV54999             No     143.832977         10.0               45.0     6472.483981
PRV56731            Yes     143.718502         20.0              100.0    14371.850227
PRV54253             No     143.587692         14.0               95.0    13640.830777
PRV51362             No     141.261324         44.0               85.0    12007.212526
PRV53683             No     137.768377          9.0               60.0     8266.102635
PRV51166             No     136.948769          5.0               70.0     9586.413824
PRV51482            Yes     134.860229         91.0               80.0    10788.818309
PRV51681             No     133.152962         26.0               75.0     9986.472181
PRV56411             No     132.533155         75.0               70.0     9277.320841
PRV52300             No     130.068135         21.0               60.0     7804.088123
PRV52127             No     129.848247         15.0              100.0    12984.824659
PRV52028             No     129.633612         18.0               85.0    11018.856995
PRV56759             No     127.265218         11.0               50.0     6363.260885
PRV51949             No     125.848959         71.0              100.0    12584.895877
PRV57208             No     125.353631        113.0               70.0     8774.754146
PRV51403             No     123.785146        114.0               75.0     9283.885982
PRV56624            Yes     123.100962         22.0              145.0    17849.639428

In [26]:
print(
    provider_features[
        [
            "ClaimAmountCV",
            "TotalClaims"
        ]
    ].corr()
)

               ClaimAmountCV  TotalClaims
ClaimAmountCV       1.000000     0.082302
TotalClaims         0.082302     1.000000

In [1]:
import os
import pandas as pd

processed_path = os.path.join(
    PROJECT_ROOT,
    "data",
    "processed",
    "provider_features.csv"
)

provider_features = pd.read_csv(processed_path)

print("Loaded provider features:", provider_features.shape)

NameError: name 'PROJECT_ROOT' is not defined

In [28]:
X = provider_features.drop(
    columns=["Provider", "PotentialFraud"]
)

y = provider_features["PotentialFraud"].map({
    "No": 0,
    "Yes": 1
})

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

X shape: (5410, 78)
y shape: (5410,)

Target distribution:
PotentialFraud
0    4904
1     506
Name: count, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\ny_train:")
print(y_train.value_counts())

print("\ny_test:")
print(y_test.value_counts())

X_train: (4328, 78)
X_test: (1082, 78)

y_train:
PotentialFraud
0    3923
1     405
Name: count, dtype: int64

y_test:
PotentialFraud
0    981
1    101
Name: count, dtype: int64

In [30]:
from src.components.model_trainer import ModelTraining

model_trainer = ModelTraining(
    random_state=42,
    cv_folds=5,
    n_iter=20
)

best_model, model_results, best_threshold = (
    model_trainer.train_models(
        X_train=X_train,
        X_test=X_test,
        y_train=y_train,
        y_test=y_test
    )
)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

CustomException: Error occurred in Python script [c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\src\components\model_trainer.py] at line [963]:
All the 100 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
100 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\.venv\Lib\site-packages\sklearn\pipeline.py", line 649, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1459, in fit
    X, y = validate_data(
           ^^^^^^^^^^^^^^
  File "c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\.venv\Lib\site-packages\sklearn\utils\validation.py", line 3055, in validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\.venv\Lib\site-packages\sklearn\utils\validation.py", line 1327, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\.venv\Lib\site-packages\sklearn\utils\validation.py", line 1087, in check_array
    _assert_all_finite(
  File "c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\.venv\Lib\site-packages\sklearn\utils\validation.py", line 137, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\.venv\Lib\site-packages\sklearn\utils\validation.py", line 186, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [2]:
import os
import pandas as pd

PROJECT_ROOT = r"C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection"

processed_path = os.path.join(
    PROJECT_ROOT,
    "data",
    "processed",
    "provider_features.csv"
)

provider_features = pd.read_csv(processed_path)

print("Shape:", provider_features.shape)
print("Columns:", len(provider_features.columns))

Shape: (5410, 80)
Columns: 80

In [3]:
X = provider_features.drop(
    columns=["Provider", "PotentialFraud"]
)

y = provider_features["PotentialFraud"].map({
    "No": 0,
    "Yes": 1
})

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

X shape: (5410, 78)
y shape: (5410,)

Target distribution:
PotentialFraud
0    4904
1     506
Name: count, dtype: int64

In [4]:
print("=" * 70)
print("FEATURE CHECK")
print("=" * 70)

for feature in [
    "HasInpatientActivity",
    "HasOutpatientActivity",
    "InpatientReimbursementRatio",
    "ReimbursementPerBeneficiary",
    "DeductiblePerBeneficiary",
    "ClaimAmountCV",
    "LogClaimAmountCV"
]:
    print(f"{feature}: {feature in X.columns}")

======================================================================
FEATURE CHECK
======================================================================
HasInpatientActivity: True
HasOutpatientActivity: True
InpatientReimbursementRatio: True
ReimbursementPerBeneficiary: True
DeductiblePerBeneficiary: True
ClaimAmountCV: True
LogClaimAmountCV: True

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("=" * 70)
print("TRAIN / TEST CHECK")
print("=" * 70)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("\ny_train:")
print(y_train.value_counts())

print("\ny_test:")
print(y_test.value_counts())

======================================================================
TRAIN / TEST CHECK
======================================================================
X_train: (4328, 78)
X_test : (1082, 78)

y_train:
PotentialFraud
0    3923
1     405
Name: count, dtype: int64

y_test:
PotentialFraud
0    981
1    101
Name: count, dtype: int64

In [6]:
print("=" * 70)
print("MISSING VALUES")
print("=" * 70)

print("Training NaN values:", X_train.isna().sum().sum())
print("Testing NaN values :", X_test.isna().sum().sum())

======================================================================
MISSING VALUES
======================================================================
Training NaN values: 41411
Testing NaN values : 10222

In [3]:
import os
import sys

PROJECT_ROOT = r"C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection"

os.chdir(PROJECT_ROOT)

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

print("Current directory:")
print(os.getcwd())

print("\nProject root in Python path:")
print(PROJECT_ROOT in sys.path)

Current directory:
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection

Project root in Python path:
True

In [4]:
from src.components.model_trainer import ModelTraining

print("ModelTraining imported successfully.")

ModelTraining imported successfully.

In [5]:
import inspect

print(
    "Loaded from:"
)
print(
    inspect.getfile(ModelTraining)
)

Loaded from:
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\src\components\model_trainer.py

In [6]:
import pandas as pd

processed_path = os.path.join(
    PROJECT_ROOT,
    "data",
    "processed",
    "provider_features.csv"
)

provider_features = pd.read_csv(processed_path)

X = provider_features.drop(
    columns=["Provider", "PotentialFraud"]
)

y = provider_features["PotentialFraud"].map({
    "No": 0,
    "Yes": 1
})

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

X_train: (4328, 78)
X_test: (1082, 78)

In [7]:
model_trainer = ModelTraining(
    random_state=42,
    cv_folds=5,
    n_iter=60
)

best_model, model_results, best_threshold = (
    model_trainer.train_models(
        X_train=X_train,
        X_test=X_test,
        y_train=y_train,
        y_test=y_test
    )
)

Fitting 5 folds for each of 60 candidates, totalling 300 fits
Fitting 5 folds for each of 60 candidates, totalling 300 fits
Fitting 5 folds for each of 60 candidates, totalling 300 fits
Fitting 5 folds for each of 60 candidates, totalling 300 fits
Fitting 5 folds for each of 60 candidates, totalling 300 fits

========================================================================================================================
MODEL TRAINING RESULTS
========================================================================================================================
              Model  CV_PR_AUC  CV_Threshold_F1  CV_Threshold_Precision  CV_Threshold_Recall  Train_Precision  Train_Recall  Train_F1  Train_PR_AUC  Train_ROC_AUC  Test_Precision  Test_Recall  Test_F1  Test_PR_AUC  Test_ROC_AUC  BestThreshold    F1_Gap
           CatBoost   0.737954         0.705069                0.660907             0.755556         0.995086      1.000000  0.997537      1.000000       1.000000        0.729730     0.801980 0.764151     0.840367      0.977796          0.500  0.233386
           LightGBM   0.747557         0.698962                0.655844             0.748148         0.955189      1.000000  0.977081      1.000000       1.000000        0.723214     0.801980 0.760563     0.830316      0.975919          0.405  0.216517
            XGBoost   0.739690         0.688971                0.691542             0.686420         0.899329      0.992593  0.943662      0.994451       0.999432        0.730000     0.722772 0.726368     0.824549      0.974960          0.710  0.217294
      Random Forest   0.696473         0.674443                0.591078             0.785185         0.775794      0.965432  0.860286      0.971973       0.996335        0.595745     0.831683 0.694215     0.800131      0.973022          0.445  0.166071
Logistic Regression   0.712895         0.665049                0.653938             0.676543         0.662621      0.674074  0.668299      0.736455       0.953427        0.685714     0.712871 0.699029     0.787703      0.969056          0.745 -0.030730

========================================================================================================================
Selected Model: CatBoost
Selected Threshold: 0.500
Model selection was based on cross-validation only.
The final test set was NOT used for model selection.
========================================================================================================================

In [13]:
import numpy as np
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score
)

# Get test probabilities from the selected model
test_prob = best_model.predict_proba(X_test)[:, 1]

threshold_results = []

for threshold in np.arange(0.05, 0.96, 0.01):

    predictions = (
        test_prob >= threshold
    ).astype(int)

    precision = precision_score(
        y_test,
        predictions,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        predictions,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        predictions,
        zero_division=0
    )

    threshold_results.append({
        "Threshold": threshold,
        "Precision": precision,
        "Recall": recall,
        "F1": f1
    })

threshold_df = pd.DataFrame(
    threshold_results
)

print(
    threshold_df
    .sort_values("F1", ascending=False)
    .head(15)
    .to_string(index=False)
)

 Threshold  Precision   Recall       F1
      0.57   0.728070 0.821782 0.772093
      0.58   0.736364 0.801980 0.767773
      0.60   0.740741 0.792079 0.765550
      0.56   0.715517 0.821782 0.764977
      0.59   0.733945 0.792079 0.761905
      0.55   0.709402 0.821782 0.761468
      0.63   0.750000 0.772277 0.760976
      0.64   0.754902 0.762376 0.758621
      0.62   0.742857 0.772277 0.757282
      0.61   0.742857 0.772277 0.757282
      0.54   0.694215 0.831683 0.756757
      0.65   0.760000 0.752475 0.756219
      0.49   0.677165 0.851485 0.754386
      0.51   0.677165 0.851485 0.754386
      0.52   0.677165 0.851485 0.754386

In [14]:
print("Maximum F1:", threshold_df["F1"].max())

print("\nBest precision:")
print(
    threshold_df
    .sort_values("Precision", ascending=False)
    .head(10)
    .to_string(index=False)
)

print("\nThresholds with Precision >= 0.80:")
print(
    threshold_df[
        threshold_df["Precision"] >= 0.80
    ]
    .sort_values("F1", ascending=False)
    .head(10)
    .to_string(index=False)
)

print("\nThresholds with Recall >= 0.90:")
print(
    threshold_df[
        threshold_df["Recall"] >= 0.90
    ]
    .sort_values("F1", ascending=False)
    .head(10)
    .to_string(index=False)
)

Maximum F1: 0.772093023255814

Best precision:
 Threshold  Precision   Recall       F1
      0.94   0.955556 0.425743 0.589041
      0.95   0.954545 0.415842 0.579310
      0.92   0.921569 0.465347 0.618421
      0.93   0.916667 0.435644 0.590604
      0.91   0.890909 0.485149 0.628205
      0.90   0.879310 0.504950 0.641509
      0.89   0.863636 0.564356 0.682635
      0.88   0.857143 0.594059 0.701754
      0.87   0.837838 0.613861 0.708571
      0.84   0.822785 0.643564 0.722222

Thresholds with Precision >= 0.80:
 Threshold  Precision   Recall       F1
      0.78   0.804598 0.693069 0.744681
      0.79   0.804598 0.693069 0.744681
      0.80   0.811765 0.683168 0.741935
      0.81   0.819277 0.673267 0.739130
      0.82   0.817073 0.663366 0.732240
      0.83   0.814815 0.653465 0.725275
      0.84   0.822785 0.643564 0.722222
      0.85   0.822785 0.643564 0.722222
      0.87   0.837838 0.613861 0.708571
      0.86   0.818182 0.623762 0.707865

Thresholds with Recall >= 0.90:
 Threshold  Precision   Recall       F1
      0.24   0.513812 0.920792 0.659574
      0.25   0.513812 0.920792 0.659574
      0.26   0.516854 0.910891 0.659498
      0.27   0.520000 0.900990 0.659420
      0.28   0.520000 0.900990 0.659420
      0.23   0.505435 0.920792 0.652632
      0.22   0.492063 0.920792 0.641379
      0.18   0.477387 0.940594 0.633333
      0.21   0.481865 0.920792 0.632653
      0.20   0.476923 0.920792 0.628378

In [2]:
import pandas as pd
import os
processed_path = os.path.join(
    PROJECT_ROOT,
    "data",
    "processed",
    "provider_features.csv"
)

provider_features = pd.read_csv(processed_path)

X = provider_features.drop(
    columns=["Provider", "PotentialFraud"]
)

y = provider_features["PotentialFraud"].map({
    "No": 0,
    "Yes": 1
})

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

NameError: name 'PROJECT_ROOT' is not defined

In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().resolve()

while project_root.name.lower() != "healthcare-insurance-claim-fraud-detection":
    if project_root.parent == project_root:
        break
    project_root = project_root.parent

sys.path.insert(0, str(project_root))

print("Project root:", project_root)

Project root: C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection

In [2]:
from src.components.data_transformation import DataTransformation
from src.components.model_trainer import ModelTraining

print("Imports successful")

Imports successful

In [3]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd().resolve()

while project_root.name.lower() != "healthcare-insurance-claim-fraud-detection":
    if project_root.parent == project_root:
        break
    project_root = project_root.parent

feature_path = (
    project_root
    / "data"
    / "processed"
    / "provider_features.csv"
)

provider_features = pd.read_csv(feature_path)

print("Loaded:", feature_path)
print("Shape:", provider_features.shape)

Loaded: C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\processed\provider_features.csv
Shape: (5410, 123)

In [5]:
import pandas as pd
from pathlib import Path

# Find project root
project_root = Path.cwd().resolve()

while project_root.name.lower() != "healthcare-insurance-claim-fraud-detection":
    if project_root.parent == project_root:
        break
    project_root = project_root.parent

# Load the NEW feature dataset
feature_path = (
    project_root
    / "data"
    / "processed"
    / "provider_features.csv"
)

provider_features = pd.read_csv(feature_path)

print("Loaded file:", feature_path)
print("Provider features shape:", provider_features.shape)

# Create X and y
X = provider_features.drop(
    columns=["Provider", "PotentialFraud"],
    errors="ignore"
)

y = (
    provider_features["PotentialFraud"]
    .map({
        "No": 0,
        "Yes": 1
    })
    .astype(int)
)

print("\nX shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

Loaded file: C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\processed\provider_features.csv
Provider features shape: (5410, 123)

X shape: (5410, 121)
y shape: (5410,)

Target distribution:
PotentialFraud
0    4904
1     506
Name: count, dtype: int64

In [6]:
non_numeric = X.select_dtypes(
    exclude="number"
).columns.tolist()

print("Non-numeric columns:")
print(non_numeric)

Non-numeric columns:
[]

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("\ny_train:")
print(y_train.value_counts())

print("\ny_test:")
print(y_test.value_counts())

X_train: (4328, 121)
X_test : (1082, 121)

y_train:
PotentialFraud
0    3923
1     405
Name: count, dtype: int64

y_test:
PotentialFraud
0    981
1    101
Name: count, dtype: int64

In [8]:
from src.components.model_trainer import ModelTraining

model_trainer = ModelTraining(
    random_state=42,
    cv_folds=5,
    n_iter=60
)

best_model, model_results, best_threshold = (
    model_trainer.train_models(
        X_train=X_train,
        X_test=X_test,  
        y_train=y_train,
        y_test=y_test
    )
)

Fitting 5 folds for each of 60 candidates, totalling 300 fits
Fitting 5 folds for each of 60 candidates, totalling 300 fits
Fitting 5 folds for each of 60 candidates, totalling 300 fits
Fitting 5 folds for each of 60 candidates, totalling 300 fits
Fitting 5 folds for each of 60 candidates, totalling 300 fits

========================================================================================================================
MODEL TRAINING RESULTS
========================================================================================================================
              Model  CV_PR_AUC  CV_Threshold_F1  CV_Threshold_Precision  CV_Threshold_Recall  Train_Precision  Train_Recall  Train_F1  Train_PR_AUC  Train_ROC_AUC  Test_Precision  Test_Recall  Test_F1  Test_PR_AUC  Test_ROC_AUC  BestThreshold    F1_Gap
           CatBoost   0.739535         0.704358                0.673423             0.738272         0.990220      1.000000  0.995086      1.000000       1.000000        0.725664     0.811881 0.766355     0.837777      0.978835          0.575  0.228731
           LightGBM   0.747385         0.699561                0.629191             0.787654         0.838509      1.000000  0.912162      0.999896       0.999989        0.641221     0.831683 0.724138     0.835503      0.978028          0.495  0.188024
            XGBoost   0.738020         0.693548                0.650108             0.743210         0.924658      1.000000  0.960854      1.000000       1.000000        0.694915     0.811881 0.748858     0.831390      0.974597          0.575  0.211996
      Random Forest   0.705631         0.677966                0.665083             0.691358         0.737931      0.792593  0.764286      0.831553       0.974328        0.678899     0.732673 0.704762     0.800862      0.972729          0.655  0.059524
Logistic Regression   0.717481         0.669757                0.631004             0.713580         0.639738      0.723457  0.679027      0.743720       0.955837        0.658333     0.782178 0.714932     0.793396      0.966270          0.705 -0.035905

========================================================================================================================
Selected Model: CatBoost
Selected Threshold: 0.575
Model selection was based on cross-validation only.
The final test set was NOT used for model selection.
========================================================================================================================

In [9]:
import joblib
from pathlib import Path

project_root = Path.cwd().resolve()

while project_root.name.lower() != "healthcare-insurance-claim-fraud-detection":
    if project_root.parent == project_root:
        break
    project_root = project_root.parent

model_dir = project_root / "models"
model_dir.mkdir(exist_ok=True)

model_path = model_dir / "catboost_final.pkl"
threshold_path = model_dir / "catboost_threshold.txt"

joblib.dump(best_model, model_path)

with open(threshold_path, "w") as f:
    f.write(str(best_threshold))

print("Model saved to:")
print(model_path)

print("Threshold saved to:")
print(threshold_path)

print("Selected threshold:", best_threshold)

Model saved to:
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\models\catboost_final.pkl
Threshold saved to:
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\models\catboost_threshold.txt
Selected threshold: 0.5750000000000004

In [10]:
import joblib

loaded_model = joblib.load(model_path)

with open(threshold_path, "r") as f:
    loaded_threshold = float(f.read())

print("Model loaded successfully")
print("Threshold:", loaded_threshold)

Model loaded successfully
Threshold: 0.5750000000000004

In [11]:
from pathlib import Path

project_root = Path.cwd().resolve()

while project_root.name.lower() != "healthcare-insurance-claim-fraud-detection":
    if project_root.parent == project_root:
        break
    project_root = project_root.parent

print("Project root:")
print(project_root)

print("\nCSV files inside data:")
for file in (project_root / "data").rglob("*.csv"):
    print(file)

Project root:
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection

CSV files inside data:
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\processed\provider_features.csv
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\raw\test\Test-1542969243754.csv
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\raw\test\Test_Beneficiarydata-1542969243754.csv
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\raw\test\Test_Inpatientdata-1542969243754.csv
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\raw\test\Test_Outpatientdata-1542969243754.csv
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\raw\train\BENEFICIARY.csv
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\raw\train\INPATIENT.csv
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\raw\train\OUTPATIENT.csv
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\raw\train\PROVIDERS.csv

In [12]:
from pathlib import Path
import pandas as pd

project_root = Path.cwd().resolve()

while project_root.name.lower() != "healthcare-insurance-claim-fraud-detection":
    if project_root.parent == project_root:
        break
    project_root = project_root.parent

test_dir = project_root / "data" / "raw" / "test"

test_files = list(test_dir.glob("*.csv"))

print("=" * 80)
print("TEST FILE CONTENT CHECK")
print("=" * 80)

for file in test_files:

    df = pd.read_csv(file, nrows=5)

    print("\nFile:", file.name)
    print("Shape preview:", df.shape)
    print("Columns:")

    for column in df.columns:
        print("  -", column)

================================================================================
TEST FILE CONTENT CHECK
================================================================================

File: Test-1542969243754.csv
Shape preview: (5, 1)
Columns:
  - Provider

File: Test_Beneficiarydata-1542969243754.csv
Shape preview: (5, 25)
Columns:
  - BeneID
  - DOB
  - DOD
  - Gender
  - Race
  - RenalDiseaseIndicator
  - State
  - County
  - NoOfMonths_PartACov
  - NoOfMonths_PartBCov
  - ChronicCond_Alzheimer
  - ChronicCond_Heartfailure
  - ChronicCond_KidneyDisease
  - ChronicCond_Cancer
  - ChronicCond_ObstrPulmonary
  - ChronicCond_Depression
  - ChronicCond_Diabetes
  - ChronicCond_IschemicHeart
  - ChronicCond_Osteoporasis
  - ChronicCond_rheumatoidarthritis
  - ChronicCond_stroke
  - IPAnnualReimbursementAmt
  - IPAnnualDeductibleAmt
  - OPAnnualReimbursementAmt
  - OPAnnualDeductibleAmt

File: Test_Inpatientdata-1542969243754.csv
Shape preview: (5, 30)
Columns:
  - BeneID
  - ClaimID
  - ClaimStartDt
  - ClaimEndDt
  - Provider
  - InscClaimAmtReimbursed
  - AttendingPhysician
  - OperatingPhysician
  - OtherPhysician
  - AdmissionDt
  - ClmAdmitDiagnosisCode
  - DeductibleAmtPaid
  - DischargeDt
  - DiagnosisGroupCode
  - ClmDiagnosisCode_1
  - ClmDiagnosisCode_2
  - ClmDiagnosisCode_3
  - ClmDiagnosisCode_4
  - ClmDiagnosisCode_5
  - ClmDiagnosisCode_6
  - ClmDiagnosisCode_7
  - ClmDiagnosisCode_8
  - ClmDiagnosisCode_9
  - ClmDiagnosisCode_10
  - ClmProcedureCode_1
  - ClmProcedureCode_2
  - ClmProcedureCode_3
  - ClmProcedureCode_4
  - ClmProcedureCode_5
  - ClmProcedureCode_6

File: Test_Outpatientdata-1542969243754.csv
Shape preview: (5, 27)
Columns:
  - BeneID
  - ClaimID
  - ClaimStartDt
  - ClaimEndDt
  - Provider
  - InscClaimAmtReimbursed
  - AttendingPhysician
  - OperatingPhysician
  - OtherPhysician
  - ClmDiagnosisCode_1
  - ClmDiagnosisCode_2
  - ClmDiagnosisCode_3
  - ClmDiagnosisCode_4
  - ClmDiagnosisCode_5
  - ClmDiagnosisCode_6
  - ClmDiagnosisCode_7
  - ClmDiagnosisCode_8
  - ClmDiagnosisCode_9
  - ClmDiagnosisCode_10
  - ClmProcedureCode_1
  - ClmProcedureCode_2
  - ClmProcedureCode_3
  - ClmProcedureCode_4
  - ClmProcedureCode_5
  - ClmProcedureCode_6
  - DeductibleAmtPaid
  - ClmAdmitDiagnosisCode

In [13]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd().resolve()

while project_root.name.lower() != "healthcare-insurance-claim-fraud-detection":
    if project_root.parent == project_root:
        break
    project_root = project_root.parent

test_dir = project_root / "data" / "raw" / "test"

print("=" * 80)
print("TEST TARGET CHECK")
print("=" * 80)

for file in test_dir.glob("*.csv"):

    df = pd.read_csv(file, nrows=5)

    print(f"\n{file.name}")
    print("PotentialFraud present:",
          "PotentialFraud" in df.columns)

    if "PotentialFraud" in df.columns:
        print(df["PotentialFraud"].value_counts())

================================================================================
TEST TARGET CHECK
================================================================================

Test-1542969243754.csv
PotentialFraud present: False

Test_Beneficiarydata-1542969243754.csv
PotentialFraud present: False

Test_Inpatientdata-1542969243754.csv
PotentialFraud present: False

Test_Outpatientdata-1542969243754.csv
PotentialFraud present: False

In [14]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd().resolve()

while project_root.name.lower() != "healthcare-insurance-claim-fraud-detection":
    if project_root.parent == project_root:
        break
    project_root = project_root.parent

test_dir = project_root / "data" / "raw" / "test"

test_files = list(test_dir.glob("*.csv"))

print("Test files found:", len(test_files))

for file in test_files:
    df = pd.read_csv(file)
    print(f"{file.name}: {df.shape}")

Test files found: 4
Test-1542969243754.csv: (1353, 1)
Test_Beneficiarydata-1542969243754.csv: (63968, 25)
Test_Inpatientdata-1542969243754.csv: (9551, 30)
Test_Outpatientdata-1542969243754.csv: (125841, 27)

In [16]:
def identify_test_file(df):
    columns = set(df.columns)

    if "Provider" in columns and "BeneID" not in columns:
        return "provider"

    if "BeneID" in columns and "ClaimID" not in columns:
        return "beneficiary"

    if "ClaimID" in columns and "AdmissionDt" in columns:
        return "inpatient"

    if "ClaimID" in columns and "AdmissionDt" not in columns:
        return "outpatient"

    return "unknown"

In [17]:
identified_files = {}

for file in test_files:
    df = pd.read_csv(file)

    file_type = identify_test_file(df)

    identified_files[file_type] = df

    print(
        f"{file.name}  -->  {file_type}"
    )

Test-1542969243754.csv  -->  provider
Test_Beneficiarydata-1542969243754.csv  -->  beneficiary
Test_Inpatientdata-1542969243754.csv  -->  inpatient
Test_Outpatientdata-1542969243754.csv  -->  outpatient

In [18]:
import sys
from pathlib import Path

project_root = Path.cwd().resolve()

while project_root.name.lower() != "healthcare-insurance-claim-fraud-detection":
    if project_root.parent == project_root:
        break
    project_root = project_root.parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

print("Project root:", project_root)

Project root: C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection

In [19]:
from src.components.feature_engineering import FeatureEngineering

print("FeatureEngineering imported successfully.")

FeatureEngineering imported successfully.

In [20]:
test_provider = identified_files["provider"].copy()
test_beneficiary = identified_files["beneficiary"].copy()
test_inpatient = identified_files["inpatient"].copy()
test_outpatient = identified_files["outpatient"].copy()

print("Provider:", test_provider.shape)
print("Beneficiary:", test_beneficiary.shape)
print("Inpatient:", test_inpatient.shape)
print("Outpatient:", test_outpatient.shape)

Provider: (1353, 1)
Beneficiary: (63968, 25)
Inpatient: (9551, 30)
Outpatient: (125841, 27)

In [21]:
import inspect

print(inspect.signature(
    FeatureEngineering
))

print("\nMethods:")
print([
    name for name in dir(FeatureEngineering)
    if not name.startswith("_")
])

() -> 'None'

Methods:
['build_provider_features']

In [22]:
print(
    inspect.signature(
        FeatureEngineering.create_features
    )
)

AttributeError: type object 'FeatureEngineering' has no attribute 'create_features'

In [23]:
import inspect

print("=" * 80)
print("FEATURE ENGINEERING CLASS")
print("=" * 80)

print("\nClass:")
print(FeatureEngineering)

print("\nPublic methods and their signatures:")

for name in dir(FeatureEngineering):
    if not name.startswith("_"):
        obj = getattr(FeatureEngineering, name)

        if callable(obj):
            try:
                print(f"\n{name}{inspect.signature(obj)}")
            except:
                print(f"\n{name}")

================================================================================
FEATURE ENGINEERING CLASS
================================================================================

Class:
<class 'src.components.feature_engineering.FeatureEngineering'>

Public methods and their signatures:

build_provider_features(self, provider_df: 'pd.DataFrame', beneficiary_df: 'pd.DataFrame', inpatient_df: 'pd.DataFrame', outpatient_df: 'pd.DataFrame') -> 'pd.DataFrame'

In [24]:
print("\nConstructor:")
print(inspect.signature(FeatureEngineering.__init__))

Constructor:
(self) -> 'None'

In [25]:
# Create feature engineering object
feature_engineer = FeatureEngineering()

# Build provider-level features from the unseen test data
test_provider_features = feature_engineer.build_provider_features(
    provider_df=test_provider,
    beneficiary_df=test_beneficiary,
    inpatient_df=test_inpatient,
    outpatient_df=test_outpatient
)

print("=" * 80)
print("TEST FEATURE ENGINEERING RESULT")
print("=" * 80)

print("Shape:", test_provider_features.shape)

print("\nFirst 5 rows:")
display(test_provider_features.head())

CustomException: Error occurred in Python script [C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\src\components\feature_engineering.py] at line [2877]: Provider dataset is missing columns: {'PotentialFraud'}

In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().resolve()

while project_root.name.lower() != "healthcare-insurance-claim-fraud-detection":
    if project_root.parent == project_root:
        break
    project_root = project_root.parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.components.feature_engineering import FeatureEngineering

print("FeatureEngineering imported successfully.")
print("Loaded from:", __import__(
    "src.components.feature_engineering",
    fromlist=["__file__"]
).__file__)

FeatureEngineering imported successfully.
Loaded from: C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\src\components\feature_engineering.py

In [2]:
import pandas as pd

test_dir = project_root / "data" / "raw" / "test"

test_provider = pd.read_csv(
    test_dir / "Test-1542969243754.csv"
)

test_beneficiary = pd.read_csv(
    test_dir / "Test_Beneficiarydata-1542969243754.csv"
)

test_inpatient = pd.read_csv(
    test_dir / "Test_Inpatientdata-1542969243754.csv"
)

test_outpatient = pd.read_csv(
    test_dir / "Test_Outpatientdata-1542969243754.csv"
)

print("Provider:", test_provider.shape)
print("Beneficiary:", test_beneficiary.shape)
print("Inpatient:", test_inpatient.shape)
print("Outpatient:", test_outpatient.shape)

Provider: (1353, 1)
Beneficiary: (63968, 25)
Inpatient: (9551, 30)
Outpatient: (125841, 27)

In [3]:
feature_engineer = FeatureEngineering()

test_provider_features = feature_engineer.build_provider_features(
    provider_df=test_provider,
    beneficiary_df=test_beneficiary,
    inpatient_df=test_inpatient,
    outpatient_df=test_outpatient
)

print("=" * 80)
print("TEST FEATURE ENGINEERING RESULT")
print("=" * 80)

print("Shape:", test_provider_features.shape)
print("Columns:", len(test_provider_features.columns))

print(
    "PotentialFraud present:",
    "PotentialFraud" in test_provider_features.columns
)

print(
    "Duplicate columns:",
    test_provider_features.columns.duplicated().sum()
)

print(
    "Duplicate rows:",
    test_provider_features.duplicated().sum()
)

================================================================================
TEST FEATURE ENGINEERING RESULT
================================================================================
Shape: (1353, 122)
Columns: 122
PotentialFraud present: False
Duplicate columns: 0
Duplicate rows: 0

In [4]:
required_features = [
    "HasInpatientActivity",
    "HasOutpatientActivity",
    "InpatientReimbursementRatio",
    "ReimbursementPerBeneficiary",
    "DeductiblePerBeneficiary",
    "ClaimAmountCV",
    "LogClaimAmountCV",
    "ClaimAmountIQR",
    "ClaimAmountOutlierRatio",
    "TopBeneficiaryClaimShare",
    "MonthlyClaimCV",
    "TotalReimbursementPercentile"
]

print("\nRequired feature check:")

for feature in required_features:
    print(
        f"{feature}:",
        feature in test_provider_features.columns
    )

Required feature check:
HasInpatientActivity: True
HasOutpatientActivity: True
InpatientReimbursementRatio: False
ReimbursementPerBeneficiary: False
DeductiblePerBeneficiary: False
ClaimAmountCV: True
LogClaimAmountCV: True
ClaimAmountIQR: True
ClaimAmountOutlierRatio: True
TopBeneficiaryClaimShare: True
MonthlyClaimCV: True
TotalReimbursementPercentile: True

In [5]:
# Load the training provider feature dataset
training_features = pd.read_csv(
    project_root / "data" / "processed" / "provider_features.csv"
)

print("Training shape:", training_features.shape)
print("Test shape:", test_provider_features.shape)

# Remove non-feature columns
training_model_features = [
    col for col in training_features.columns
    if col not in ["Provider", "PotentialFraud"]
]

test_model_features = [
    col for col in test_provider_features.columns
    if col != "Provider"
]

print("\nTraining model features:", len(training_model_features))
print("Test model features:", len(test_model_features))

# Features required by training but missing from test
missing_from_test = sorted(
    set(training_model_features) - set(test_model_features)
)

# Features present in test but not training
extra_in_test = sorted(
    set(test_model_features) - set(training_model_features)
)

print("\n" + "=" * 80)
print("FEATURE COMPARISON")
print("=" * 80)

print("\nMissing from TEST:")
for feature in missing_from_test:
    print(" -", feature)

print("\nExtra in TEST:")
for feature in extra_in_test:
    print(" -", feature)

print("\nNumber missing:", len(missing_from_test))
print("Number extra:", len(extra_in_test))

Training shape: (5410, 123)
Test shape: (1353, 122)

Training model features: 121
Test model features: 121

================================================================================
FEATURE COMPARISON
================================================================================

Missing from TEST:

Extra in TEST:

Number missing: 0
Number extra: 0

In [6]:
features_to_check = [
    "InpatientReimbursementRatio",
    "ReimbursementPerBeneficiary",
    "DeductiblePerBeneficiary"
]

print("=" * 80)
print("TRAINING FEATURE VALUES")
print("=" * 80)

for feature in features_to_check:
    print(f"\n{feature}")

    if feature in training_features.columns:
        print("Present in training: True")
        print(training_features[feature].describe())
    else:
        print("Present in training: False")

================================================================================
TRAINING FEATURE VALUES
================================================================================

InpatientReimbursementRatio
Present in training: False

ReimbursementPerBeneficiary
Present in training: False

DeductiblePerBeneficiary
Present in training: False

In [7]:
# Make sure test columns are in EXACTLY the same order as training

X_test_unseen = test_provider_features[
    training_model_features
].copy()

print("=" * 80)
print("FINAL TEST FEATURE ALIGNMENT")
print("=" * 80)

print("Shape:", X_test_unseen.shape)
print("Expected features:", len(training_model_features))
print("Actual features:", len(X_test_unseen.columns))

print(
    "Column order matches:",
    list(X_test_unseen.columns) == training_model_features
)

================================================================================
FINAL TEST FEATURE ALIGNMENT
================================================================================
Shape: (1353, 121)
Expected features: 121
Actual features: 121
Column order matches: True

In [8]:
print("=" * 80)
print("TEST MISSING VALUE CHECK")
print("=" * 80)

missing_values = X_test_unseen.isna().sum()

missing_values = (
    missing_values[missing_values > 0]
    .sort_values(ascending=False)
)

print("Total missing values:", X_test_unseen.isna().sum().sum())

if len(missing_values) > 0:
    print("\nFeatures containing missing values:")
    print(missing_values)
else:
    print("No missing values found.")

================================================================================
TEST MISSING VALUE CHECK
================================================================================
Total missing values: 16158

Features containing missing values:
ClaimDurationCV                            1184
UniqueProcedureCount                        854
ProceduresPerClaim                          854
AverageInpatientDeductible                  835
InpatientReimbursement                      833
InpatientAverageClaim                       833
InpatientMaximumClaim                       833
MaximumInpatientClaimDuration               833
AverageInpatientClaimDuration               833
MaximumHospitalStay                         833
AverageHospitalStay                         833
LongClaimDurationRatio                      833
LongHospitalStayCount                       833
LongHospitalStayRatio                       833
HighValueInpatientClaimRatio                833
MaximumHospitalStayPercentile               833
MaximumHospitalStayVsPeerMedian             833
ClaimsPerOperatingPhysicianPercentile       142
ClaimsPerOperatingPhysicianVsPeerMedian     142
ClaimsPerOperatingPhysician                 142
ClaimsPerOtherPhysician                     115
OutpatientAverageClaim                       94
OutpatientReimbursement                      94
MaximumOutpatientClaimDuration               94
AverageOutpatientDeductible                  94
LongOutpatientClaimDurationRatio             94
HighValueOutpatientClaimRatio                94
AverageOutpatientClaimDuration               94
OutpatientMaximumClaim                       94
MonthlyClaimStd                              52
MonthlyClaimCV                               52
BeneficiaryClaimStd                          50
ClaimAmountStd                               49
ClaimAmountCV                                49
LogClaimAmountCV                             49
DeductibleToReimbursementRatio                2
ClaimAmountMeanMedianRatio                    2
ClaimAmountOutlierRatio                       2
DeductibleToReimbursementAdvanced             2
dtype: int64

In [9]:
import joblib

model_path = project_root / "models" / "catboost_final.pkl"
threshold_path = project_root / "models" / "catboost_threshold.txt"

print("Model exists:", model_path.exists())
print("Threshold exists:", threshold_path.exists())

loaded_model = joblib.load(model_path)

with open(threshold_path, "r") as f:
    loaded_threshold = float(f.read())

print("\nModel loaded successfully.")
print("Threshold:", loaded_threshold)

Model exists: True
Threshold exists: True

Model loaded successfully.
Threshold: 0.5750000000000004

In [10]:
# Generate probability of PotentialFraud = 1

fraud_probability = loaded_model.predict_proba(
    X_test_unseen
)[:, 1]

print("=" * 80)
print("PREDICTION CHECK")
print("=" * 80)

print("Number of predictions:", len(fraud_probability))
print("Minimum probability:", fraud_probability.min())
print("Maximum probability:", fraud_probability.max())
print("Average probability:", fraud_probability.mean())

================================================================================
PREDICTION CHECK
================================================================================
Number of predictions: 1353
Minimum probability: 0.0004409544257768745
Maximum probability: 0.9964620584727479
Average probability: 0.12310543575559572

c:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but SimpleImputer was fitted without feature names
  warnings.warn(

In [11]:
test_predictions = (
    fraud_probability >= loaded_threshold
).astype(int)

print("=" * 80)
print("UNSEEN TEST PREDICTIONS")
print("=" * 80)

print("Total providers:", len(test_predictions))

print(
    "Predicted Fraud:",
    (test_predictions == 1).sum()
)

print(
    "Predicted Non-Fraud:",
    (test_predictions == 0).sum()
)

print(
    "Predicted Fraud %:",
    round(
        (test_predictions == 1).mean() * 100,
        2
    )
)

================================================================================
UNSEEN TEST PREDICTIONS
================================================================================
Total providers: 1353
Predicted Fraud: 139
Predicted Non-Fraud: 1214
Predicted Fraud %: 10.27

In [12]:
test_results = pd.DataFrame({
    "Provider": test_provider["Provider"].values,
    "FraudProbability": fraud_probability,
    "Prediction": test_predictions
})

test_results["Prediction"] = test_results["Prediction"].map({
    0: "Non-Fraud",
    1: "Potential Fraud"
})

test_results = test_results.sort_values(
    "FraudProbability",
    ascending=False
).reset_index(drop=True)

print("=" * 80)
print("FINAL UNSEEN TEST RESULTS")
print("=" * 80)

display(test_results.head(20))

================================================================================
FINAL UNSEEN TEST RESULTS
================================================================================

    Provider  FraudProbability       Prediction
0   PRV56460          0.996462  Potential Fraud
1   PRV54948          0.996422  Potential Fraud
2   PRV53610          0.996112  Potential Fraud
3   PRV53758          0.995423  Potential Fraud
4   PRV51407          0.995297  Potential Fraud
5   PRV51073          0.995106  Potential Fraud
6   PRV51982          0.994686  Potential Fraud
7   PRV56573          0.994148  Potential Fraud
8   PRV54751          0.993936  Potential Fraud
9   PRV53866          0.993898  Potential Fraud
10  PRV55478          0.993745  Potential Fraud
11  PRV55485          0.992996  Potential Fraud
12  PRV52338          0.992186  Potential Fraud
13  PRV53105          0.991445  Potential Fraud
14  PRV54766          0.990118  Potential Fraud
15  PRV57323          0.989219  Potential Fraud
16  PRV54094          0.987820  Potential Fraud
17  PRV56024          0.987476  Potential Fraud
18  PRV52618          0.986051  Potential Fraud
19  PRV53275          0.982401  Potential Fraud

In [13]:
output_path = (
    project_root
    / "data"
    / "processed"
    / "test_provider_predictions.csv"
)

test_results.to_csv(
    output_path,
    index=False
)

print("Prediction file saved:")
print(output_path)

Prediction file saved:
C:\Users\suriy\Desktop\Healthcare-Insurance-claim-fraud-detection\data\processed\test_provider_predictions.csv